[project]
name = "aws-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artur Makowski", email = "artmak1@st.amu.edu.pl" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
aws-python = "aws_python:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
]
test = [
    "pytest>=8.3.4",
]
