# ship the fastapi metrics, traces, and logs to AWS

services:
  fastapi:
    image: files-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      AWS_ENDPOINT_URL: http://aws-mock:5001
      S3_BUCKET_NAME: mocked-bucket
      AWS_REGION: mock
      AWS_ACCESS_KEY_ID: mock # pragma: allowlist secret
      AWS_SECRET_ACCESS_KEY: mock # pragma: allowlist secret
      OPENAI_BASE_URL: http://openai-mock:1080 # pragma: allowlist secret
      OPENAI_API_KEY: mocked_key # pragma: allowlist secret
    depends_on:
      - aws-mock
      - openai-mock
    volumes:
      - ../:/app
  aws-mock:
    image: motoserver/moto:latest
    command: "-p5001"
    ports:
      - "5001:5001"
  openai-mock:
    image: openai-mock
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: python ./tests/mocks/openai_fastapi_mock_app.py
    environment:
      OPENAI_MOCK_PORT: "1080"
    ports:
      - "1080:1080"
    volumes:
      - ../:/app
  logspout:
    # Logs: uses the docker daemon to collect logs from fastapi's stdout and push to cloudwatch
    image: mdsol/logspout:0.9.0
    platform: linux/amd64
    command: "cloudwatch://${AWS_REGION:-us-east-1}?NOEC2"
    environment:
      EXCLUDE_LABELS: "logspout=disable"
      LOGSPOUT_GROUP: /aws/lambda/local-fastapi
      # DEBUG: "1"  # enable this line for verbose logs to debug logspout
      LOGSPOUT_STREAM: "{{.Name}}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    # Generate the .env file with this command:
    # aws configure export-credentials --profile $AWS_PROFILE --format env > .env
    env_file:
      - ../.env
